{% set name = "album-solution-api" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fb91360ce1e0dbbc6527cf7d3c0533a036d835fb1919344cb0600793158c8c11

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - album.runner
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://album.solutions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Album is a framework for unifying computational tools across frameworks, languages, and environments.
  doc_url: https://docs.album.solutions
  dev_url: https://gitlab.com/album-app/album-solution-api

extra:
  recipe-maintainers:
    - frauzufall
