{% set name = "album-solution-api" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e11d7f11cdfb631ed1840237c68c7444cbd0a401920d1cdf2e94257959082667

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - album.runner
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://album.solutions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Album is a framework for unifying computational tools across frameworks, languages, and environments.
  doc_url: https://docs.album.solutions
  dev_url: https://gitlab.com/album-app/album-solution-api

extra:
  recipe-maintainers:
    - frauzufall
